train_dataset: image-folder
train_dataset_args: 
    root_path:  /mnt/disk1/workspace/Datasets/imagenet/ILSVRC2012_img_256_train
    split_file: ./materials/imagenet-800_split.json
    split: base

val_dataset: image-folder
val_dataset_args:
    root_path: /mnt/disk1/workspace/Datasets/ILSVRC2012_img_validation
    split_file: ./materials/imagenet-800_split.json
    split: novel

model: meta-baseline
model_args: 
    encoder: resnet50
    encoder_args: {}
load_encoder: ./save/im800-resnet50.pth

freeze_bn: True

n_way: 5
n_shot: 10
n_query: 15
train_batches: 500
ep_per_batch: 1

max_epoch: 50
optimizer: sgd
optimizer_args: {lr: 0.001, weight_decay: 1.e-4}

visualize_datasets: True
