train_dataset: mini-imagenet
train_dataset_args: {split: train, augment: resize}
val_dataset: mini-imagenet
val_dataset_args: {split: train_phase_val}


model: classifier
model_args:
    encoder: rfs-resnet12
    encoder_args: {}
    classifier: linear-classifier 
    classifier_args: {n_classes: 64}
#load: ./save/mini-resnet12.pth

batch_size: 60
max_epoch: 90
optimizer: sgd
optimizer_args: {lr: 0.05, weight_decay: 5.e-4, milestones: [60, 80]}

save_epoch: 5
visualize_datasets: true
